# Generated by Django 6.0.4 on 2026-04-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50)),
                ('court', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=100)),
                ('filing_date', models.DateField()),
                ('disposal_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
